import type { Incident, Stats } from './types'

export const MOCK_INCIDENTS: Incident[] = [
  {
    id: 'TW-SOCIAL-001',
    status: 'geoparsing',
    severity: 'high',
    location: {
      lat: -0.4506,
      lng: 129.8856,
      desa: 'Pulau Gag',
      kecamatan: 'Waigeo Barat Kepulauan',
      kabupaten: 'Raja Ampat',
      provinsi: 'Papua Barat Daya',
    },
    violation_type: 'protected_area_breach',
    zone_name: 'Pulau Gag and adjacent Raja Ampat reef seascape',
    zone_type: 'High-biodiversity coastal and reef-linked livelihood zone',
    violation_flag: true,
    change_score: 0.68,
    ndvi_before: 0.72,
    ndvi_after: 0.36,
    area_ha: 188,
    post_text: 'Public X post amplified the warning: "Raja Ampat bukan untuk ditambang," linking nickel mining to reef, tourism, and livelihood risk.',
    post_date: '2025-06-05T08:55:00Z',
    report_date: '2025-06-05',
    source_type: 'public_social_post',
    source_name: 'Gerakan Rakyat on X',
    source_url: 'https://x.com/gerakanrakyatid/status/1930609308418630014',
    source_date: '2025-06-05',
    concession_holder: 'PT Gag Nikel / Raja Ampat nickel mining controversy',
    lease_context: {
      name: 'GAG NIKEL',
      license_type: 'KK',
      activity: 'OPERASI PRODUKSI',
      commodity: 'NIKEL',
      area_ha: 13136,
      polygon: [
        { lat: -0.5, lng: 129.9 },
        { lat: -0.5, lng: 129.891667 },
        { lat: -0.508333, lng: 129.891667 },
        { lat: -0.508333, lng: 129.858333 },
        { lat: -0.508333, lng: 129.85 },
        { lat: -0.491667, lng: 129.85 },
        { lat: -0.491667, lng: 129.833333 },
        { lat: -0.408333, lng: 129.833333 },
        { lat: -0.408333, lng: 129.85 },
        { lat: -0.4, lng: 129.85 },
        { lat: -0.4, lng: 129.858333 },
        { lat: -0.391667, lng: 129.858333 },
        { lat: -0.391667, lng: 129.866667 },
        { lat: -0.383333, lng: 129.866667 },
        { lat: -0.383333, lng: 129.933333 },
        { lat: -0.466667, lng: 129.933333 },
        { lat: -0.466667, lng: 129.916667 },
        { lat: -0.491667, lng: 129.916667 },
        { lat: -0.491667, lng: 129.908333 },
        { lat: -0.5, lng: 129.908333 },
        { lat: -0.5, lng: 129.9 },
      ],
    },
    location_proxy: {
      method: 'Text-to-lease narrowing: Raja Ampat + nickel mining -> GAG NIKEL production lease',
      confidence: 'lease-backed proxy',
      uncertainty_km: 2.8,
      evidence: [
        'Post text names Raja Ampat and nickel mining risk',
        'WIUP_2025 contains a GAG NIKEL production polygon in Raja Ampat',
        'Proxy is anchored to the lease polygon, not the district centroid',
      ],
    },
  },
  {
    id: 'TW-REAL-001',
    status: 'verified',
    severity: 'critical',
    location: {
      lat: 1.1089,
      lng: 127.7312,
      desa: 'Maba Pura',
      kecamatan: 'Kota Maba',
      kabupaten: 'Halmahera Timur',
      provinsi: 'Maluku Utara',
    },
    violation_type: 'tailings_discharge',
    zone_name: 'Teluk Buli and adjacent mangrove coastline',
    zone_type: 'Coastal and mangrove ecosystem',
    violation_flag: true,
    change_score: 0.93,
    ndvi_before: 0.76,
    ndvi_after: 0.18,
    area_ha: 41.2,
    post_text: 'Local reporting described mining runoff reaching the coast near Maba Pura, with sediment threatening mangroves and nearshore fishing grounds.',
    post_date: '2021-05-04T06:00:00Z',
    report_date: '2021-05-04',
    source_type: 'investigation',
    source_name: 'Mongabay Indonesia',
    source_url: 'https://mongabay.co.id/2021/05/04/tambang-antam-cemari-pesisir-halmahera-timur/',
    source_date: '2021-05-04',
    concession_holder: 'PT Aneka Tambang (site Moronopo / Tanjung Buli)',
  },
  {
    id: 'TW-REAL-002',
    status: 'routed',
    severity: 'critical',
    location: {
      lat: 1.091,
      lng: 127.767,
      desa: 'Buli',
      kecamatan: 'Maba',
      kabupaten: 'Halmahera Timur',
      provinsi: 'Maluku Utara',
    },
    violation_type: 'river_contamination',
    zone_name: 'Teluk Buli coastal waters',
    zone_type: 'Fishing and coastal livelihood zone',
    violation_flag: true,
    change_score: 0.9,
    ndvi_before: 0.7,
    ndvi_after: 0.12,
    area_ha: 57.6,
    post_text: 'A 2024 report summarized research showing severe sedimentation and dissolved heavy metals in Teluk Buli, with impacts on fish and food safety.',
    post_date: '2024-01-02T05:00:00Z',
    report_date: '2024-01-02',
    source_type: 'investigation',
    source_name: 'Mongabay Indonesia',
    source_url: 'https://mongabay.co.id/2024/01/02/laut-halmahera-timur-tercemar-parah-limbah-nikel/',
    source_date: '2024-01-02',
    concession_holder: 'Nickel operations around Teluk Buli',
  },
  {
    id: 'TW-REAL-003',
    status: 'verified',
    severity: 'high',
    location: {
      lat: -4.321,
      lng: 123.161,
      desa: 'Roko-Roko Raya',
      kecamatan: 'Wawonii Tenggara',
      kabupaten: 'Konawe Kepulauan',
      provinsi: 'Sulawesi Tenggara',
    },
    violation_type: 'river_contamination',
    zone_name: 'Village spring and household water catchment',
    zone_type: 'Community freshwater source',
    violation_flag: true,
    change_score: 0.79,
    ndvi_before: 0.61,
    ndvi_after: 0.24,
    area_ha: 18.5,
    post_text: 'Residents reported that freshwater sources turned turbid after nickel mining began operating, making household water unsafe and deepening conflict on the island.',
    post_date: '2023-06-09T04:00:00Z',
    report_date: '2023-06-09',
    source_type: 'local_news',
    source_name: 'Betahita',
    source_url: 'https://www.betahita.id/news/detail/8869/kala-pertambangan-nikel-beroperasi-di-wawonii.html?v=1686513869',
    source_date: '2023-06-09',
    concession_holder: 'PT Gema Kreasi Perdana',
  },
  {
    id: 'TW-REAL-004',
    status: 'routed',
    severity: 'critical',
    location: {
      lat: -4.304,
      lng: 123.154,
      desa: 'Dompo-Dompo Jaya',
      kecamatan: 'Wawonii Tenggara',
      kabupaten: 'Konawe Kepulauan',
      provinsi: 'Sulawesi Tenggara',
    },
    violation_type: 'tailings_discharge',
    zone_name: 'Five-village coastal stretch in Southeast Wawonii',
    zone_type: 'Small-island coastal zone',
    violation_flag: true,
    change_score: 0.85,
    ndvi_before: 0.67,
    ndvi_after: 0.16,
    area_ha: 33.4,
    post_text: 'Civil society groups documented muddy coastal waters affecting five villages in Southeast Wawonii after nickel extraction intensified on the island.',
    post_date: '2023-06-15T04:00:00Z',
    report_date: '2023-06-15',
    source_type: 'local_news',
    source_name: 'Betahita',
    source_url: 'https://betahita.id/news/detail/8846/menanti-audit-lingkungan-tambang-nikel-di-wawonii.html?v=1687214917',
    source_date: '2023-06-15',
    concession_holder: 'PT Gema Kreasi Perdana',
  },
  {
    id: 'TW-REAL-005',
    status: 'verified',
    severity: 'high',
    location: {
      lat: -3.882,
      lng: 122.345,
      desa: 'Kapoiala Baru',
      kecamatan: 'Kapoiala',
      kabupaten: 'Konawe',
      provinsi: 'Sulawesi Tenggara',
    },
    violation_type: 'protected_area_breach',
    zone_name: 'Mangrove and brackish-water aquaculture belt',
    zone_type: 'Coastal livelihood ecosystem',
    violation_flag: true,
    change_score: 0.74,
    ndvi_before: 0.69,
    ndvi_after: 0.28,
    area_ha: 64.8,
    post_text: 'Reporting from Konawe described collapsing crab harvests and shrinking tambak areas as nickel mining and smelting expanded around Morosi and nearby coasts.',
    post_date: '2026-03-04T03:00:00Z',
    report_date: '2026-03-04',
    source_type: 'investigation',
    source_name: 'Mongabay Indonesia',
    source_url: 'https://mongabay.co.id/2026/03/04/terdampak-industri-nikel-panen-kepiting-konawe-terus-tergerus/',
    source_date: '2026-03-04',
    concession_holder: 'Industrial nickel corridor around Morosi / VDNI / OSS',
  },
  {
    id: 'TW-REAL-006',
    status: 'verified',
    severity: 'critical',
    location: {
      lat: -5.282,
      lng: 121.876,
      desa: 'Baliara',
      kecamatan: 'Kabaena Barat',
      kabupaten: 'Bombana',
      provinsi: 'Sulawesi Tenggara',
    },
    violation_type: 'tailings_discharge',
    zone_name: 'Kabaena coastal settlements and nearshore waters',
    zone_type: 'Small-island marine and settlement zone',
    violation_flag: true,
    change_score: 0.91,
    ndvi_before: 0.72,
    ndvi_after: 0.11,
    area_ha: 96.3,
    post_text: 'A 2025 investigation described widespread sediment-laden coasts and dangerous heavy metal exposure risks in Kabaena after years of nickel extraction.',
    post_date: '2025-02-12T05:00:00Z',
    report_date: '2025-02-12',
    source_type: 'investigation',
    source_name: 'Mongabay Indonesia',
    source_url: 'https://mongabay.co.id/2025/02/12/nasib-warga-kala-tambang-nikel-kuasai-pulau-kabaena/',
    source_date: '2025-02-12',
    concession_holder: 'Multiple nickel permit holders in Kabaena',
  },
  {
    id: 'TW-REAL-007',
    status: 'satellite',
    severity: 'high',
    location: {
      lat: 0.4512,
      lng: 127.5623,
      desa: 'Sagea',
      kecamatan: 'Weda Utara',
      kabupaten: 'Halmahera Tengah',
      provinsi: 'Maluku Utara',
    },
    violation_type: 'illegal_clearing',
    zone_name: 'Upper watershed linked to Sungai Sagea',
    zone_type: 'Forest and karst-linked watershed',
    violation_flag: true,
    change_score: 0.77,
    ndvi_before: 0.82,
    ndvi_after: 0.34,
    area_ha: 72.9,
    post_text: 'Residents in Sagea described upstream nickel expansion that dirtied the river system connected to Gua Bokimaruru and threatened remaining forest cover.',
    post_date: '2024-09-17T04:00:00Z',
    report_date: '2024-09-17',
    source_type: 'investigation',
    source_name: 'Mongabay Indonesia',
    source_url: 'https://mongabay.co.id/2024/09/17/lingkungan-halmahera-tengah-terus-tergerus-industri-nikel/',
    source_date: '2024-09-17',
    concession_holder: 'Nickel expansion in the Sagea watershed',
  },
  {
    id: 'TW-REAL-008',
    status: 'landuse',
    severity: 'high',
    location: {
      lat: 0.333,
      lng: 127.568,
      desa: 'Lelilef Woebulen',
      kecamatan: 'Weda Tengah',
      kabupaten: 'Halmahera Tengah',
      provinsi: 'Maluku Utara',
    },
    violation_type: 'river_contamination',
    zone_name: 'Ale Doma and Kobe river corridor',
    zone_type: 'River and community water-use zone',
    violation_flag: true,
    change_score: 0.71,
    ndvi_before: 0.64,
    ndvi_after: 0.29,
    area_ha: 28.1,
    post_text: 'Communities in Weda Tengah reported rivers turning orange to dark brown after nickel mining and industrial activity intensified around their villages.',
    post_date: '2022-07-17T05:00:00Z',
    report_date: '2022-07-17',
    source_type: 'investigation',
    source_name: 'Mongabay Indonesia',
    source_url: 'https://mongabay.co.id/2022/07/17/nasib-sungai-di-halmahera-tengah-kala-industri-nikel-datang-2/',
    source_date: '2022-07-17',
    concession_holder: 'Nickel operations in Weda Tengah / IWIP corridor',
  },

  // National news sources
  {
    id: 'TW-KOMPAS-001',
    status: 'routed',
    severity: 'critical',
    location: {
      lat: -2.956,
      lng: 121.968,
      desa: 'Fatufia',
      kecamatan: 'Bahodopi',
      kabupaten: 'Morowali',
      provinsi: 'Sulawesi Tengah',
    },
    violation_type: 'tailings_discharge',
    zone_name: 'Morowali Bay coastal strip and mangrove fringe',
    zone_type: 'Coastal and mangrove ecosystem',
    violation_flag: true,
    change_score: 0.88,
    ndvi_before: 0.71,
    ndvi_after: 0.14,
    area_ha: 112.4,
    post_text: 'Kompas reported that fishermen in Bahodopi described nets returning full of dark sediment instead of fish, tracing the source to nickel smelter runoff entering Morowali Bay.',
    post_date: '2023-08-14T04:00:00Z',
    report_date: '2023-08-14',
    source_type: 'national_news',
    source_name: 'Kompas',
    source_url: 'https://www.kompas.com/sains/read/2023/08/14/090000023/limbah-nikel-morowali',
    source_date: '2023-08-14',
    concession_holder: 'PT Indonesia Morowali Industrial Park (IMIP) corridor',
  },
  {
    id: 'TW-KOMPAS-002',
    status: 'verified',
    severity: 'high',
    location: {
      lat: -2.614,
      lng: 121.522,
      desa: 'Bungku Pesisir',
      kecamatan: 'Bungku Pesisir',
      kabupaten: 'Morowali',
      provinsi: 'Sulawesi Tengah',
    },
    violation_type: 'river_contamination',
    zone_name: 'Bungku coastal estuary and fishing grounds',
    zone_type: 'Coastal livelihood zone',
    violation_flag: true,
    change_score: 0.76,
    ndvi_before: 0.65,
    ndvi_after: 0.22,
    area_ha: 45.7,
    post_text: 'Kompas documented communities in Bungku Pesisir reporting red-brown river discharge from upstream nickel processing facilities reaching their estuary and coastal fishing areas.',
    post_date: '2024-03-22T05:00:00Z',
    report_date: '2024-03-22',
    source_type: 'national_news',
    source_name: 'Kompas',
    source_url: 'https://www.kompas.com/sains/read/2024/03/22/pencemaran-sungai-morowali-nikel',
    source_date: '2024-03-22',
    concession_holder: 'Nickel processing corridor, Bungku district',
  },
  {
    id: 'TW-TEMPO-001',
    status: 'routed',
    severity: 'critical',
    location: {
      lat: -0.435,
      lng: 129.872,
      desa: 'Waigeo Selatan',
      kecamatan: 'Waigeo Selatan',
      kabupaten: 'Raja Ampat',
      provinsi: 'Papua Barat Daya',
    },
    violation_type: 'protected_area_breach',
    zone_name: 'Raja Ampat marine conservation corridor',
    zone_type: 'UNESCO-adjacent biodiversity hotspot',
    violation_flag: true,
    change_score: 0.72,
    ndvi_before: 0.74,
    ndvi_after: 0.31,
    area_ha: 203.1,
    post_text: 'Tempo\'s investigation revealed that nickel concession surveys in Raja Ampat proceeded despite the archipelago being classified as a coral triangle priority zone, with local fishers reporting vessel traffic in no-take areas.',
    post_date: '2019-09-03T06:00:00Z',
    report_date: '2019-09-03',
    source_type: 'national_news',
    source_name: 'Tempo',
    source_url: 'https://www.tempo.co/hukum/tambang-nikel-raja-ampat-2019',
    source_date: '2019-09-03',
    concession_holder: 'PT Gag Nikel / concession survey operators',
  },
  {
    id: 'TW-TEMPO-002',
    status: 'verified',
    severity: 'high',
    location: {
      lat: -3.641,
      lng: 122.316,
      desa: 'Lasolo',
      kecamatan: 'Lasolo',
      kabupaten: 'Konawe Utara',
      provinsi: 'Sulawesi Tenggara',
    },
    violation_type: 'illegal_clearing',
    zone_name: 'Lasolo river watershed and upstream forest',
    zone_type: 'Protected watershed and community water source',
    violation_flag: true,
    change_score: 0.81,
    ndvi_before: 0.78,
    ndvi_after: 0.27,
    area_ha: 87.3,
    post_text: 'Tempo reported that illegal clearing for nickel exploration in Konawe Utara had stripped protective forest cover from the Lasolo watershed, with downstream villages recording turbid water within weeks.',
    post_date: '2022-04-11T05:00:00Z',
    report_date: '2022-04-11',
    source_type: 'national_news',
    source_name: 'Tempo',
    source_url: 'https://www.tempo.co/lingkungan/tambang-nikel-konawe-utara-2022',
    source_date: '2022-04-11',
    concession_holder: 'Nickel exploration permits, Konawe Utara',
  },
  {
    id: 'TW-ANTARA-001',
    status: 'verified',
    severity: 'high',
    location: {
      lat: 1.873,
      lng: 127.621,
      desa: 'Kao',
      kecamatan: 'Kao',
      kabupaten: 'Halmahera Utara',
      provinsi: 'Maluku Utara',
    },
    violation_type: 'river_contamination',
    zone_name: 'Kao Bay and river delta',
    zone_type: 'Bay and delta fishing zone',
    violation_flag: true,
    change_score: 0.69,
    ndvi_before: 0.62,
    ndvi_after: 0.28,
    area_ha: 53.2,
    post_text: 'Antara News reported that nickel mining expansion in North Halmahera had pushed sediment loads into Kao Bay, reducing fish catch volumes and prompting community complaints to district authorities.',
    post_date: '2020-11-05T06:00:00Z',
    report_date: '2020-11-05',
    source_type: 'national_news',
    source_name: 'Antara News',
    source_url: 'https://www.antaranews.com/berita/1830000/tambang-nikel-halmahera-utara-cemari-teluk-kao',
    source_date: '2020-11-05',
    concession_holder: 'Nickel operations in Kao district, Halmahera Utara',
  },
  {
    id: 'TW-CNN-001',
    status: 'routed',
    severity: 'critical',
    location: {
      lat: -3.075,
      lng: 122.008,
      desa: 'Fatufia',
      kecamatan: 'Bahodopi',
      kabupaten: 'Morowali',
      provinsi: 'Sulawesi Tengah',
    },
    violation_type: 'tailings_discharge',
    zone_name: 'IMIP coastal boundary, Bahodopi',
    zone_type: 'Heavy industrial coastal transition zone',
    violation_flag: true,
    change_score: 0.94,
    ndvi_before: 0.68,
    ndvi_after: 0.09,
    area_ha: 148.6,
    post_text: 'CNN Indonesia broadcast footage from Topogaro showing black-grey tailings discharge entering the sea from the IMIP industrial zone perimeter, with residents describing the smell as unbearable during tidal shifts.',
    post_date: '2023-11-29T06:00:00Z',
    report_date: '2023-11-29',
    source_type: 'national_news',
    source_name: 'CNN Indonesia',
    source_url: 'https://www.cnnindonesia.com/ekonomi/nikel-morowali-limbah-2023',
    source_date: '2023-11-29',
    concession_holder: 'PT Indonesia Morowali Industrial Park (IMIP)',
  },
  {
    id: 'TW-X-GECKO001',
    status: 'geoparsing',
    severity: 'high',
    location: {
      lat: -1.47,
      lng: 127.43,
      desa: 'Kawasi',
      kecamatan: 'Obi',
      kabupaten: 'Halmahera Selatan',
      provinsi: 'Maluku Utara',
    },
    violation_type: 'tailings_discharge',
    zone_name: 'Harita nickel coastal zone, Pulau Obi',
    zone_type: 'coastal',
    violation_flag: true,
    change_score: 0.78,
    ndvi_before: 0.0,
    ndvi_after: 0.0,
    area_ha: 0,
    post_text: 'TERUNGKAP: Tambang nikel Harita mengetahui pencemaran ikan dekat tambangnya pada 2022 di Pulau Obi, Maluku Utara. Namun Harita menghapus peringatan tersebut, dan tidak membukanya ke publik.',
    post_date: '2025-11-23T07:00:00Z',
    report_date: '2025-11-23',
    source_type: 'social_media',
    source_name: 'The Gecko Project (X)',
    source_url: 'https://x.com/geckoproj/status/1990375969300132067',
    source_date: '2025-11-23',
    concession_holder: 'PT Trimegah Bangun Persada (Harita Nickel)',
  },
]

export const MOCK_STATS: Stats = {
  total_incidents: 15,
  verified: 11,
  violations_flagged: 15,
  area_cleared_ha: 1072,
  provinces_active: 4,
}
